version: '3'
services:
  ap:
    image: python:3.6.1
    ports:
    - "5000:5000"
    env_file:
    - env_files/ap
    volumes:
    - .:/usr/src/app
    command: bash /usr/src/app/docker_bin/start
    working_dir: /usr/src/app
