version: '3'
services:
  ap:
    image: python:3.6.1
    ports:
    - "5000:5000"
    env_file:
    - env_file/ap
    volumes:
    - .:/usr/src/app
    - ../docker_bin:/docker_bin
    - ../source_script:/source_script
    command: bash /usr/src/app/docker_bin/start
    working_dir: /usr/src/app
